# Generated by Django 4.1.2 on 2023-02-02 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_alter_category_options_alter_person_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Тип статуса')),
            ],
        ),
        migrations.AlterField(
            model_name='status',
            name='type',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.SET_DEFAULT, to='mysite.types', verbose_name='Тип статуса'),
        ),
    ]
