# Generated by Django 4.1.7 on 2023-03-13 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0009_request_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': ['-datetime'], 'verbose_name': 'Запрос', 'verbose_name_plural': 'Запросы'},
        ),
        migrations.AlterField(
            model_name='request',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/', verbose_name='Фото'),
        ),
    ]
