# Generated by Django 4.1.7 on 2023-03-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0010_alter_request_options_alter_request_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='img',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='Фото'),
        ),
    ]
