# Generated by Django 4.1.7 on 2023-03-26 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mysite', '0012_alter_request_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': ['-datetime'], 'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Запрос', 'verbose_name_plural': 'Запросы'},
        ),
        migrations.AlterModelOptions(
            name='types',
            options={'verbose_name': 'Статус', 'verbose_name_plural': 'Статусы'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='status',
            name='category',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='mysite.category', verbose_name='Тип статуса'),
        ),
        migrations.AlterField(
            model_name='status',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время запроса'),
        ),
        migrations.AlterField(
            model_name='status',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.request', verbose_name='Заявка'),
        ),
        migrations.AlterField(
            model_name='status',
            name='type',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.SET_DEFAULT, to='mysite.types', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='status',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='types',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Наименование статусы'),
        ),
    ]
