# Generated by Django 4.2 on 2023-04-06 06:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mysite', '0013_alter_request_options_alter_status_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Статус', 'verbose_name_plural': 'Статусы'},
        ),
        migrations.AlterModelOptions(
            name='types',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AddField(
            model_name='request',
            name='on_del',
            field=models.BooleanField(default=False, verbose_name='Статус удаления пользователем'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='request',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='request',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.types', verbose_name='Категория запроса'),
        ),
        migrations.AlterField(
            model_name='types',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Наименование категории'),
        ),
    ]
